### ISSUE TITLE
При первом старте упало на экране ввода имени пользователя

### ISSUE THREAD

**Issue by dtrounine** [KorolevaYana/SMSToTelegram#1]
```
FATAL EXCEPTION: main
Process: ru.ifmo.droid2016.smstotelegram, PID: 32757
java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
at ru.ifmo.droid2016.smstotelegram.activities.SelectionActivity$2.handleMessage(SelectionActivity.java:105)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:7007)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

http://take.ms/jfWUZ

**Comment by KorolevaYana** [comment]
Fixed/
